export function createActivities({action,close,identity,send,notify}){
 const root=document.createElement('section');root.id='activities';root.hidden=true;document.querySelector('.tool-panel').append(root);
 let mode='',raf=0,last=0,score=0,playing=false,x=1,y=1,dir=[0,0],want=[0,0],dots=new Set(),enemies=[],stepAt=0,lives=3,runnerY=0,vy=0,obstacles=[],spawnAt=0,time=0,keys=new Set();
 const maze=['#####################','#....#.........#....#','#.##.#.###.###.#.##.#','#....#...#.#...#....#','###.###.#...#.###.###','#.......#.#.#.......#','#.#####.#.#.#.#####.#','#.........#.........#','#.###.#########.###.#','#...#.....#.....#...#','###.###.#.#.#.###.###','#.......#...#.......#','#####################'];
 function open(which){stop();mode=which;root.hidden=false;
  if(which==='catalog'){root.innerHTML='<p>물건을 선택하면 게임 안에서 설치 위치를 확인합니다.</p><div class="catalog-grid"></div>';for(const[k,name]of Object.entries({chair:'의자',table:'책상',sofa:'소파',bed:'침대',book:'책',marker:'보드마카',crate:'상자',gun:'장난감 총',shield:'방패',plate:'접시'})){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{action('build_begin',{kind:k});close()};root.firstElementChild.nextElementSibling.append(b)}return}
  root.innerHTML=`<p>${which==='maze'?'정원 미로: 방향키로 씨앗을 모으고 순찰 로봇을 피하세요. 세 번 닿으면 종료됩니다.':'작은 공룡 달리기: Space/↑로 점프해 화분을 피하세요. 시간이 갈수록 빨라집니다.'} · 직접 만든 규칙/그림</p><div class="row"><button id="arcadeStart">시작 / 재시작</button><span id="arcadeScore">준비</span></div><canvas id="arcadeCanvas" width="840" height="520" tabindex="0"></canvas>`;
  root.querySelector('#arcadeStart').onclick=start;draw();root.querySelector('canvas').focus();last=performance.now();raf=requestAnimationFrame(loop)
 }
 function start(){score=0;lives=3;playing=true;time=0;runnerY=0;vy=0;obstacles=[];spawnAt=.8;x=1;y=1;dir=[0,0];want=[0,0];dots=new Set();for(let j=0;j<maze.length;j++)for(let i=0;i<maze[j].length;i++)if(maze[j][i]==='.')dots.add(i+','+j);dots.delete('1,1');enemies=[{x:19,y:1},{x:1,y:11},{x:19,y:11}];stepAt=0;root.querySelector('canvas').focus()}
 function stop(){cancelAnimationFrame(raf);raf=0;playing=false;keys.clear()}
 function finish(won=false){playing=false;send({type:'arcade-result',game:mode,score,won});notify((won?'미로 수집 완료':'게임 종료')+' · '+score+'점')}
 function loop(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(playing){time+=dt;if(mode==='runner'){
   vy-=1100*dt;runnerY=Math.max(0,runnerY+vy*dt);if(runnerY===0)vy=0;spawnAt-=dt;if(spawnAt<=0){obstacles.push({x:870,w:25+Math.random()*28,h:35+Math.random()*32});spawnAt=1.0+Math.random()*.7}const speed=Math.min(500,230+time*4);for(const o of obstacles)o.x-=speed*dt;obstacles=obstacles.filter(o=>o.x>-80);score=Math.floor(time*10);for(const o of obstacles)if(o.x<145&&o.x+o.w>108&&runnerY<o.h-8)finish();
  }else if(time-stepAt>.13){stepAt=time;const free=(a,b)=>maze[b]?.[a]&&maze[b][a]!=='#';if(free(x+want[0],y+want[1]))dir=want;if(free(x+dir[0],y+dir[1])){x+=dir[0];y+=dir[1]}if(dots.delete(x+','+y))score+=10;if(Math.floor(time*10)%3!==0)for(const e of enemies){const options=[[1,0],[-1,0],[0,1],[0,-1]].filter(([a,b])=>free(e.x+a,e.y+b));options.sort((a,b)=>Math.hypot(e.x+a[0]-x,e.y+a[1]-y)-Math.hypot(e.x+b[0]-x,e.y+b[1]-y));const next=options[Math.random()<.75?0:Math.floor(Math.random()*options.length)];if(next){e.x+=next[0];e.y+=next[1]}}if(enemies.some(e=>e.x===x&&e.y===y)){lives--;x=1;y=1;enemies=[{x:19,y:1},{x:1,y:11},{x:19,y:11}];if(!lives)finish()}if(!dots.size)finish(true)}
  if(Math.floor(time*10)%5===0)send({type:'arcade-progress',game:mode,score})
 }draw();raf=requestAnimationFrame(loop)}
 function draw(){const canvas=root.querySelector('canvas');if(!canvas)return;const c=canvas.getContext('2d');c.fillStyle='#e6e3cc';c.fillRect(0,0,840,520);
  if(mode==='maze'){const cell=40;for(let j=0;j<maze.length;j++)for(let i=0;i<maze[j].length;i++){if(maze[j][i]==='#'){c.fillStyle='#31584b';c.fillRect(i*cell+2,j*cell+2,36,36)}else if(dots.has(i+','+j)){c.fillStyle='#b67828';c.beginPath();c.arc(i*cell+20,j*cell+20,4,0,Math.PI*2);c.fill()}}c.fillStyle='#e07b42';c.fillRect(x*40+9,y*40+9,23,23);c.fillStyle='#fff';c.fillRect(x*40+22,y*40+13,5,5);for(const e of enemies){c.fillStyle='#758fba';c.fillRect(e.x*40+8,e.y*40+8,24,24);c.fillStyle='#253f42';c.fillRect(e.x*40+12,e.y*40+13,16,5)}}else{c.fillStyle='#c8dace';c.fillRect(0,0,840,435);c.fillStyle='#5c7350';c.fillRect(0,435,840,85);c.fillStyle='#39745b';c.fillRect(110,390-runnerY,34,45);c.fillRect(132,375-runnerY,31,27);c.fillRect(94,407-runnerY,25,13);c.fillStyle='#fff';c.fillRect(149,381-runnerY,5,5);for(const o of obstacles){c.fillStyle='#b16d44';c.fillRect(o.x,435-o.h,o.w,o.h);c.fillStyle='#447957';c.beginPath();c.arc(o.x+o.w/2,435-o.h,o.w*.7,0,Math.PI*2);c.fill()}}
  root.querySelector('#arcadeScore').textContent=`${score}점 · ${mode==='maze'?lives+'번 기회':'Space 점프'}${playing?'':' · 시작 버튼으로 재시작'}`;
 }
 function key(e){if(root.hidden||!['maze','runner'].includes(mode)||/INPUT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(mode==='runner'&&['Space','ArrowUp'].includes(e.code)&&runnerY===0&&playing)vy=510;const dirs={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(dirs[e.code])want=dirs[e.code]}
 document.addEventListener('keydown',key);
 return {open,hide(){root.hidden=true;stop()},destroy(){stop();document.removeEventListener('keydown',key);root.remove()}};
}
