import {drawRunner} from './runner-renderer.mjs';
import {MAZE,newGame,input,tick} from './arcade-rules.mjs';
export function createArcade({send,isHost,id,state,notify}){
 const root=document.createElement('section');root.id='authoritativeArcade';root.hidden=true;root.innerHTML='<p id="arcadeRules"></p><div class="row"><button id="arcadeStart">규칙 확인 · 시작 / 재시작</button><span id="arcadeScore"></span></div><canvas id="arcadeCanvas" width="840" height="520" tabindex="0"></canvas>';document.querySelector('.tool-panel').append(root);const $=id=>root.querySelector('#'+id);let games={},records=[],mode='',seq=0,last=performance.now(),sendAt=0;
 const near=(who,game)=>{const p=state()?.players.find(p=>p.id===who);const x=game==='maze'?29:32;return !!p&&p.zone==='arcade'&&Math.hypot(p.p[0]-x,p.p[1],p.p[2]-4.9)<4};
 function dispatch(m){if(isHost())receive(id(),m);else send(m)}
 function open(game){game='runner';mode=game;root.hidden=false;$('arcadeRules').textContent=game==='maze'?'정원 미로 · 방향키로 씨앗을 모으고 순찰 로봇을 피하세요. 3번 닿으면 끝납니다. 기계가 사용 중이면 같은 경기를 관전합니다.':'공룡 러너 · Space/↑ 점프 · ↓/C 웅크리기 · 선인장과 새를 피하세요. 속도가 증가하고 낮/밤이 바뀝니다. 사용 중인 기계는 관전합니다.';dispatch({type:'arcade-enter',game});$('arcadeCanvas').focus();draw()}
 function hide(){if(mode)dispatch({type:'arcade-leave',game:mode});root.hidden=true;mode=''}
 function receive(sender,m){if(!m.type.startsWith('arcade-'))return false;if(!['maze','runner'].includes(m.game))return true;if(!isHost()){if(m.type==='arcade-state'){games[m.game]=m.state;draw()}return true}
  const s=games[m.game];if(m.type==='arcade-enter'){if(!near(sender,m.game))return true;if(!s||!s.owner)games[m.game]=newGame(m.game,sender,crypto.getRandomValues(new Uint32Array(1))[0]);send({type:'arcade-state',game:m.game,state:games[m.game]});draw();return true}
  if(m.type==='arcade-leave'&&s?.owner===sender){s.owner='';if(s.phase==='play')s.phase='result';publishResult(s);return true}
  if(m.type==='arcade-input'&&s?.owner===sender&&near(sender,m.game)){input(s,m);send({type:'arcade-state',game:m.game,state:s});draw()}return true;
 }
 function publishResult(s){if(s.recorded||s.phase!=='result')return;s.recorded=true;records.push({game:s.game,score:s.score,won:!!s.won});records=records.slice(-64);send({type:'arcade-state',game:s.game,state:s});notify((s.game==='maze'?'정원 미로':'공룡 달리기')+' 결과 · '+s.score+'점')}
 setInterval(()=>{const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(isHost()&&!state()?.paused)for(const s of Object.values(games)){if(s.owner&&!state()?.players.some(p=>p.id===s.owner)){s.owner='';s.phase='result'}tick(s,dt);publishResult(s)}if(isHost()&&now-sendAt>100){sendAt=now;for(const s of Object.values(games))send({type:'arcade-state',game:s.game,state:s})}if(!root.hidden)draw()},50);
 function act(op){if(!mode)return;dispatch({type:'arcade-input',game:mode,op,sequence:++seq})}$('arcadeStart').onclick=()=>{act('start');$('arcadeCanvas').focus()};
 document.addEventListener('keydown',e=>{if(root.hidden)return;const keys={jump:'jump',look_up:mode==='runner'?'jump':'up',look_down:'down',look_left:'left',look_right:'right'};const action=Object.keys(keys).find(k=>window.Homeoffice?.key_matches(e,k));if(window.Homeoffice?.key_matches(e,'crouch')||window.Homeoffice?.key_matches(e,'look_down')){e.preventDefault();act('duck');return}if(action){e.preventDefault();if(!e.repeat)act(keys[action]==='jump'&&games[mode]?.phase!=='play'?'start':keys[action])}});
 document.addEventListener('keyup',e=>{if(!root.hidden&&(window.Homeoffice?.key_matches(e,'crouch')||window.Homeoffice?.key_matches(e,'look_down')))act('stand')});
 function draw(){if(root.hidden)return;const s=games[mode]||newGame(mode,''),c=$('arcadeCanvas').getContext('2d');c.fillStyle='#e6e3cc';c.fillRect(0,0,840,520);if(mode==='maze'){const dots=new Set(s.dots);for(let y=0;y<MAZE.length;y++)for(let x=0;x<MAZE[y].length;x++){if(MAZE[y][x]==='#'){c.fillStyle='#31584b';c.fillRect(x*40+2,y*40+2,36,36)}else if(dots.has(x+','+y)){c.fillStyle='#b67828';c.beginPath();c.arc(x*40+20,y*40+20,4,0,Math.PI*2);c.fill()}}c.fillStyle='#e07b42';c.fillRect(s.x*40+9,s.y*40+9,23,23);for(const e of s.enemies){c.fillStyle='#758fba';c.fillRect(e.x*40+8,e.y*40+8,24,24);c.fillStyle='#253f42';c.fillRect(e.x*40+12,e.y*40+13,16,5)}}else{drawRunner(c,s)}const phases={rules:'규칙 확인',play:'플레이',result:'결과'};$('arcadeScore').textContent=(s.owner===id()?'내 경기':'관전')+' · '+(phases[s.phase]||s.phase)+' · '+s.score+'점 · 최고 '+Math.max(s.score,...records.filter(r=>r.game===mode).map(r=>r.score))+'점'+(mode==='maze'?' · 남은 기회 '+s.lives:'');$('arcadeStart').disabled=s.owner!==id()||s.phase==='play'}
 return {open,hide,suspend(){root.hidden=true},receive,results:()=>structuredClone(records),snapshot:()=>({games:structuredClone(games),records:structuredClone(records)}),restore(s){games=structuredClone(s?.games||{});records=structuredClone(s?.records||[]);draw()},diagnostics:()=>({mode,games,records})};
}
