export function createBoardTools({strokes,action}){
 const canvas=document.getElementById('whiteboard'),ctx=canvas.getContext('2d'),bar=document.getElementById('boardTools');let drawing=null,selected='',origin=null;
 const extra=document.createElement('span');extra.innerHTML='<select id="boardMode"><option value="pen">펜</option><option value="line">선</option><option value="rect">사각형</option><option value="ellipse">타원</option><option value="text">한글 텍스트</option><option value="select">선택·이동</option><option value="erase">항목 지우개</option></select><input id="boardText" maxlength="160" placeholder="보드에 쓸 문장"><button id="boardDelete">선택 항목 삭제</button>';
 bar.append(extra);const $=id=>document.getElementById(id);
 const point=e=>{const r=canvas.getBoundingClientRect();return [Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),Math.min(1,Math.max(0,(e.clientY-r.top)/r.height))]};
 function bounds(s){let xs=s.points.map(p=>p[0]),ys=s.points.map(p=>p[1]);return [Math.min(...xs),Math.min(...ys),Math.max(...xs)+(s.kind==='text'?Math.min(.8,s.text.length*.024):0),Math.max(...ys)+(s.kind==='text'?.065:0)]}
 function hit(p){return [...strokes()].reverse().find(s=>{const b=bounds(s);return p[0]>=b[0]-.012&&p[0]<=b[2]+.012&&p[1]>=b[1]-.02&&p[1]<=b[3]+.02})}
 function shape(points){const mode=$('boardMode').value,a=points[0],b=points.at(-1);if(mode==='line')return[a,b];if(mode==='rect')return[a,[b[0],a[1]],b,[a[0],b[1]],a];if(mode==='ellipse')return Array.from({length:49},(_,i)=>[(a[0]+b[0])/2+Math.abs(a[0]-b[0])/2*Math.cos(i/48*2*Math.PI),(a[1]+b[1])/2+Math.abs(a[1]-b[1])/2*Math.sin(i/48*2*Math.PI)]);return points}
 function paint(s){ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.lineWidth=s.width;ctx.lineCap='round';ctx.lineJoin='round';if(s.kind==='text'){ctx.font=`${s.fontSize||28}px 'Noto Sans KR',sans-serif`;ctx.textBaseline='top';ctx.fillText(s.text,s.points[0][0]*1024,s.points[0][1]*512,1000-s.points[0][0]*1024);return}ctx.beginPath();s.points.forEach((p,i)=>ctx[i?'lineTo':'moveTo'](p[0]*1024,p[1]*512));ctx.stroke()}
 function render(){ctx.fillStyle='#f4f4ed';ctx.fillRect(0,0,1024,512);for(const s of strokes())paint(s);if(drawing&&origin===null)paint({points:shape(drawing),color:$('color').value,width:+$('width').value});const s=strokes().find(s=>s.id===selected);if(s){const b=bounds(s);ctx.setLineDash([6,4]);ctx.strokeStyle='#ce943f';ctx.lineWidth=2;ctx.strokeRect(b[0]*1024-5,b[1]*512-5,(b[2]-b[0])*1024+10,(b[3]-b[1])*512+10);ctx.setLineDash([])}}
 canvas.onpointerdown=e=>{const pt=point(e),mode=$('boardMode').value;canvas.setPointerCapture(e.pointerId);if(mode==='text'){const text=$('boardText').value.trim();if(text)action('stroke',{kind:'text',text,fontSize:28,points:[pt,[Math.min(.99,pt[0]+.002),Math.min(.99,pt[1]+.002)]],color:$('color').value,width:+$('width').value});return}if(mode==='select'||mode==='erase'){const s=hit(pt);selected=s?.id||'';if(mode==='erase'&&s)action('board_delete',{id:s.id,version:s.version||0});else if(s){origin={point:pt,stroke:structuredClone(s)};drawing=[pt]}render();return}origin=null;drawing=[pt]};
 canvas.onpointermove=e=>{if(drawing&&drawing.length<256){drawing.push(point(e));render()}};
 canvas.onpointerup=e=>{if(origin&&drawing){const pt=point(e),s=origin.stroke,dx=pt[0]-origin.point[0],dy=pt[1]-origin.point[1];action('board_update',{id:s.id,version:s.version||0,points:s.points.map(p=>[Math.max(0,Math.min(1,p[0]+dx)),Math.max(0,Math.min(1,p[1]+dy))])})}else if(drawing?.length>1)action('stroke',{points:shape(drawing),color:$('color').value,width:+$('width').value});drawing=null;origin=null;render()};
 canvas.onpointercancel=()=>{drawing=null;origin=null;render()};$('boardDelete').onclick=()=>{const s=strokes().find(s=>s.id===selected);if(s)action('board_delete',{id:s.id,version:s.version||0})};
 return {render};
}
