import * as Y from 'yjs';
import Quill from 'quill';
import {QuillBinding} from 'y-quill';
const b64=a=>{let s='';for(const v of a)s+=String.fromCharCode(v);return btoa(s)};
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
export function createCollaboration({send,notify,identity}){
 let doc,binding,editor,revision=0,remote=false,view='report';const root=document.createElement('div');root.id='collaboration';root.hidden=true;
 root.innerHTML=`<nav class="tabs"><button data-tab="report">공동 보고서</button><button data-tab="brainstorm">브레인스토밍</button><button data-tab="mindmap">마인드맵</button><button data-tab="meeting">의제 · 회의 결과</button></nav><div id="reportPane"><div class="row"><button id="reportUndo">내 입력 Undo</button><button id="reportRedo">Redo</button><button id="insertTable">3×3 표</button><span>Yjs 공동 편집 · 한글 입력 가능</span></div><div id="reportEditor"></div></div><div id="cardsPane" hidden><div class="row"><input id="cardText" maxlength="180" placeholder="생각 또는 노드 이름"><select id="cardColor"><option value="#f5df9b">노랑</option><option value="#c3d8c5">초록</option><option value="#bdd2e2">파랑</option></select><input id="cardGroup" maxlength="40" placeholder="그룹"><button id="addCard">추가</button></div><div id="cardSpace"></div></div><div id="meetingPane" hidden><p>의제 → 발표/토론 → 투표 → 결론 → 할 일. 각 항목을 공동 보고서에 정리하세요.</p><label>의제 <textarea id="agenda" rows="3" maxlength="2000"></textarea></label><label>결론/할 일 <textarea id="decisions" rows="4" maxlength="3000"></textarea></label><div class="row"><button id="raiseHand">손들기 / 내리기</button><button id="meetingTimer">5분 타이머</button><span id="meetingClock"></span></div><div id="hands"></div><h3>질문 대기열</h3><div class="row"><input id="questionText" maxlength="240" placeholder="회의에서 다룰 질문"><button id="addQuestion">질문 등록</button></div><div id="questions"></div><h3>후속 할 일</h3><div class="row"><input id="taskText" maxlength="240" placeholder="실행할 일"><input id="taskOwner" maxlength="60" placeholder="담당자"><button id="addTask">할 일 등록</button></div><div id="tasks"></div></div>`;
 document.querySelector('.tool-panel').append(root);const $=id=>root.querySelector('#'+id);
 let undo, composing=false;
 function init(snapshot){
  const next=new Y.Doc();try{if(snapshot)Y.applyUpdate(next,bytes(snapshot),'restore');validateCandidate(next)}catch(e){next.destroy();throw e}binding?.destroy();doc?.destroy();doc=next;
  $('reportEditor').innerHTML='';editor=new Quill($('reportEditor'),{theme:'snow',placeholder:'제목과 회의 기록을 함께 작성하세요.',formats:['header','bold','italic','underline','list','table'],modules:{toolbar:[[{header:[1,2,false]}],['bold','italic','underline'],[{list:'ordered'},{list:'bullet'},{list:'check'}]],history:{userOnly:true},table:true}});
  binding=new QuillBinding(doc.getText('report'),editor);undo=new Y.UndoManager(doc.getText('report'),{trackedOrigins:new Set([binding])});
  editor.root.addEventListener('compositionstart',()=>{composing=true});editor.root.addEventListener('compositionend',()=>{composing=false});
  doc.on('update',(update,origin)=>{revision++;if(origin!=='remote'&&origin!=='restore')send({type:'collab',update:b64(update)});renderCards();renderMeeting()});
  renderCards();renderMeeting();
 }
 function open(mode='report'){root.hidden=false;view=mode;drawView()}
 function drawView(){$('reportPane').hidden=view!=='report';$('cardsPane').hidden=!['brainstorm','mindmap'].includes(view);$('meetingPane').hidden=view!=='meeting';renderCards();renderMeeting()}
 function textChange(el,key){let before='',relativeAnchor=null;el.addEventListener('focus',()=>{before=el.value});el.addEventListener('compositionstart',()=>{el.dataset.composing='1';before=el.value});el.addEventListener('compositionend',()=>{delete el.dataset.composing;commit()});el.addEventListener('input',()=>{if(!el.dataset.composing)commit()});function commit(){const t=doc.getText(key),old=t.toString(),value=el.value;let start=0;while(start<old.length&&start<value.length&&old[start]===value[start])start++;let end=0;while(end<old.length-start&&end<value.length-start&&old[old.length-1-end]===value[value.length-1-end])end++;doc.transact(()=>{if(old.length-start-end)t.delete(start,old.length-start-end);if(value.length-start-end)t.insert(start,value.slice(start,value.length-end))},el);before=value}}
 textChange($('agenda'),'agenda');textChange($('decisions'),'decisions');
 function renderMeeting(){for(const key of ['agenda','decisions']){const el=$(key);if(el.dataset.composing)continue;const val=doc.getText(key).toString();if(el.value!==val){const a=el.selectionStart,b=el.selectionEnd;el.value=val;el.setSelectionRange(Math.min(a,val.length),Math.min(b,val.length))}}$('hands').textContent='손든 사람: '+[...doc.getMap('hands').entries()].filter(x=>x[1]).map(x=>x[0].slice(-6)).join(', ');renderQueue('questions');renderQueue('tasks')}
 function renderQueue(kind){const container=$(kind);container.replaceChildren();for(const[key,item]of [...doc.getMap(kind)].sort((a,b)=>a[1].createdAt-b[1].createdAt)){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=(item.done?'✓ ':'○ ')+item.text+(item.owner?' · '+item.owner:'');const done=document.createElement('button');done.textContent=item.done?'다시 열기':kind==='questions'?'답변 완료':'완료';done.onclick=()=>{const current=doc.getMap(kind).get(key);if(current)doc.getMap(kind).set(key,{...current,done:!current.done})};const remove=document.createElement('button');remove.textContent='삭제';remove.onclick=()=>doc.getMap(kind).delete(key);row.append(label,done,remove);container.append(row)}}
 function addQueue(kind,text,owner=''){const value=text.trim();if(!value)return;const map=doc.getMap(kind);if(map.size>=80)return notify('종류별 최대 80개입니다');map.set(crypto.randomUUID(),{text:value.slice(0,240),owner:owner.trim().slice(0,60),author:identity(),done:false,createdAt:Date.now()})}
 $('addQuestion').onclick=()=>{addQueue('questions',$('questionText').value);$('questionText').value=''};
 $('addTask').onclick=()=>{addQueue('tasks',$('taskText').value,$('taskOwner').value);$('taskText').value=''};
 function renderCards(){if(!['brainstorm','mindmap'].includes(view))return;const space=$('cardSpace');space.replaceChildren();const map=doc.getMap(view);const cards=[...map.entries()];
  if(view==='mindmap'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('mindlines');for(const[,v]of cards){if(!v.parent)continue;const parent=map.get(v.parent);if(!parent)continue;const line=document.createElementNS(svg.namespaceURI,'line');for(const[k,val]of Object.entries({x1:parent.x+90,y1:parent.y+45,x2:v.x+90,y2:v.y+45,stroke:'#406555','stroke-width':3}))line.setAttribute(k,val);svg.append(line)}space.append(svg)}
  for(const[id,v]of cards){const card=document.createElement('article');card.className='idea-card';card.style.cssText=`left:${Math.max(0,Math.min(750,v.x))}px;top:${Math.max(0,Math.min(420,v.y))}px;background:${['#f5df9b','#c3d8c5','#bdd2e2'].includes(v.color)?v.color:'#f5df9b'}`;const drag=document.createElement('div');drag.className='card-handle';drag.textContent=view==='mindmap'?'↔ 노드 이동':'↔ 메모 이동';const content=document.createElement('textarea');content.value=v.text;content.maxLength=180;content.onchange=()=>map.set(id,{...map.get(id),text:content.value});const group=document.createElement('small');group.textContent=v.group||'';const vote=document.createElement('button');const votes=doc.getMap('votes');vote.textContent='투표 '+[...votes.keys()].filter(k=>k.startsWith(id+':')).length;vote.onclick=()=>{const key=id+':'+identity();votes.has(key)?votes.delete(key):votes.set(key,true)};const del=document.createElement('button');del.textContent='삭제';del.onclick=()=>map.delete(id);card.append(drag,content,group,vote,del);
   if(view==='mindmap'){const sel=document.createElement('select');sel.append(new Option('상위 노드 없음',''));for(const[pid,pv]of cards)if(pid!==id)sel.append(new Option(pv.text.slice(0,24),pid));sel.value=v.parent||'';sel.onchange=()=>{let at=sel.value;const seen=new Set([id]);while(at){if(seen.has(at)){notify('순환 연결은 만들 수 없습니다');return}seen.add(at);at=map.get(at)?.parent}map.set(id,{...map.get(id),parent:sel.value})};card.append(sel)}
   let start=null;drag.onpointerdown=e=>{start={x:e.clientX,y:e.clientY,ox:v.x,oy:v.y};drag.setPointerCapture(e.pointerId)};drag.onpointermove=e=>{if(start){card.style.left=Math.max(0,Math.min(750,start.ox+e.clientX-start.x))+'px';card.style.top=Math.max(0,Math.min(420,start.oy+e.clientY-start.y))+'px'}};drag.onpointerup=e=>{if(start){map.set(id,{...map.get(id),x:Math.max(0,Math.min(750,start.ox+e.clientX-start.x)),y:Math.max(0,Math.min(420,start.oy+e.clientY-start.y))});start=null}};space.append(card)
  }
 }
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{view=b.dataset.tab;drawView()});
 $('addCard').onclick=()=>{if(!$('cardText').value.trim())return;const map=doc.getMap(view);if(map.size>=80)return notify('메모는 종류별 80개까지입니다');const id=crypto.randomUUID();map.set(id,{text:$('cardText').value,color:$('cardColor').value,group:$('cardGroup').value,x:25+(map.size%4)*200,y:20+Math.floor(map.size/4)*115,parent:''});$('cardText').value=''};
 $('reportUndo').onclick=()=>undo.undo();$('reportRedo').onclick=()=>undo.redo();$('insertTable').onclick=()=>editor.getModule('table').insertTable(3,3);
 $('raiseHand').onclick=()=>{const m=doc.getMap('hands');m.set(identity(),!m.get(identity()))};$('meetingTimer').onclick=()=>doc.getMap('meeting').set('timerEnd',Date.now()+300000);
 const timer=setInterval(()=>{$('meetingClock').textContent=Math.max(0,Math.ceil(((doc?.getMap('meeting').get('timerEnd')||0)-Date.now())/1000))+'초'},500);
 function validateCandidate(candidate){for(const kind of ['questions','tasks']){const map=candidate.getMap(kind);if(map.size>80)throw Error('질문/할 일 개수 한도');for(const[key,v]of map){if(typeof key!=='string'||key.length>100||!v||typeof v.text!=='string'||v.text.length>240||typeof v.owner!=='string'||v.owner.length>60||typeof v.author!=='string'||v.author.length>100||typeof v.done!=='boolean'||!Number.isFinite(v.createdAt))throw Error('잘못된 질문/할 일')}}if(Y.encodeStateAsUpdate(candidate).length>2*1024*1024)throw Error('문서 용량 한도');for(const[k]of candidate.share)if(!['report','agenda','decisions','brainstorm','mindmap','votes','hands','meeting','questions','tasks'].includes(k))throw Error('허용하지 않는 문서 종류');for(const d of candidate.getText('report').toDelta()){if(typeof d.insert!=='string')throw Error('임베드 실행 금지');if(d.attributes&&Object.keys(d.attributes).some(k=>!['header','bold','italic','underline','list','table'].includes(k)))throw Error('허용되지 않는 서식')}for(const type of ['brainstorm','mindmap']){if(candidate.getMap(type).size>80)throw Error('메모 한도');for(const v of candidate.getMap(type).values()){if(!v||typeof v.text!=='string'||v.text.length>180||!Number.isFinite(v.x)||!Number.isFinite(v.y))throw Error('잘못된 메모')}}}
 function receive(m){try{if(typeof m.update!=='string'||m.update.length>3e6||!/^[A-Za-z0-9+/]*={0,2}$/.test(m.update))return false;const update=bytes(m.update);const candidate=new Y.Doc();Y.applyUpdate(candidate,Y.encodeStateAsUpdate(doc));Y.applyUpdate(candidate,update);validateCandidate(candidate);candidate.destroy();Y.applyUpdate(doc,update,'remote');return true}catch(e){notify('공동 편집 연산 거절: '+e.message);return false}}
 function validateSnapshot(s){const next=new Y.Doc();try{if(s?.update)Y.applyUpdate(next,bytes(s.update));validateCandidate(next);return true}finally{next.destroy()}}
 init();return {open,validate:validateSnapshot,hide(){root.hidden=true},receive,snapshot(){return {update:b64(Y.encodeStateAsUpdate(doc)),revision}},restore(s){init(s?.update);revision=s?.revision||0},diagnostics(){return {report:doc.getText('report').toString(),revision,brainstorm:doc.getMap('brainstorm').toJSON(),mindmap:doc.getMap('mindmap').toJSON(),questions:doc.getMap('questions').toJSON(),tasks:doc.getMap('tasks').toJSON(),agenda:doc.getText('agenda').toString(),decisions:doc.getText('decisions').toString(),composing}},destroy(){clearInterval(timer);binding?.destroy();doc.destroy();root.remove()}};
}
