const CATALOG=[['chair','의자','0.54 × 1.14 × 0.54 m'],['table','책상','2.8 × 0.82 × 1.2 m'],['sofa','소파','2.7 × 1.09 × 1.04 m'],['bed','침대','1.19 × 1.17 × 2.14 m'],['book','책','0.24 × 0.08 × 0.32 m'],['crate','상자','0.44 × 0.44 × 0.44 m'],['gun','장난감 총','0.12 × 0.33 × 0.42 m'],['shield','방패','0.69 × 0.91 × 0.21 m'],['plate','접시','0.4 × 0.04 × 0.4 m'],['storage','수납함','1.24 × 0.67 × 0.93 m'],['drawer','서랍장','0.96 × 0.83 × 0.66 m'],['floor_lamp','스탠드 조명','0.5 × 1.66 × 0.5 m']];
export function createPlacementPanel({canvas,push,onOpen,onClose}){
 const root=document.createElement('aside');root.id='placementPanel';root.hidden=true;root.setAttribute('aria-label','물건 설치함');
 root.innerHTML='<div class="placement-heading"><h2>물건 설치</h2><button type="button" aria-label="설치함 닫기">닫기</button></div><p>썸네일을 공간으로 끌어 놓으세요.</p><input type="search" aria-label="설치할 물건 검색" placeholder="물건 찾기"><div class="placement-options"><button type="button" id="placementRotate">45° 회전 · R</button><label><input id="placementSnap" type="checkbox" checked> 25cm 스냅</label></div><p id="placementStatus" role="status">가까운 지지면 위에 설치할 수 있습니다.</p><div class="placement-cards"></div><p class="fine">초록: 설치 가능 · 빨강: 설치 불가<br>Esc, 창 포커스 해제 또는 패널 안에 놓으면 취소됩니다.</p>';
 document.body.append(root);const cards=root.querySelector('.placement-cards'),status=root.querySelector('#placementStatus');
 let drag=null,lastResult={},dropped=0,cancelled=0,raf=0,pending=null,angle=0;
 for(const[kind,label,size]of CATALOG){const b=document.createElement('button');b.type='button';b.className='placement-card';b.dataset.kind=kind;b.dataset.label=label;b.setAttribute('aria-label',label+' 끌어 놓기');b.innerHTML=`<img src="catalog/${kind}.png" alt="" draggable="false"><strong>${label}</strong><small>${size}</small>`;b.addEventListener('pointerdown',e=>begin(e,kind,b));cards.append(b);}
 function point(e){const r=canvas.getBoundingClientRect(),hit=document.elementFromPoint(e.clientX,e.clientY);return {u:(e.clientX-r.left)/r.width,v:(e.clientY-r.top)/r.height,inside:hit===canvas&&e.clientX>=r.left&&e.clientX<r.right&&e.clientY>=r.top&&e.clientY<r.bottom};}
 function send(move){push({type:'placement',...move});}
 function flush(){cancelAnimationFrame(raf);raf=0;if(pending&&drag){send({...pending,phase:'move',token:drag.token,angle,snap:root.querySelector('#placementSnap').checked});pending=null;}}
 function begin(e,kind,card){if(e.button!==0||drag)return;e.preventDefault();e.stopImmediatePropagation();drag={token:crypto.randomUUID(),kind,pointerId:e.pointerId,card};angle=0;card.setPointerCapture(e.pointerId);root.classList.add('dragging');send({phase:'begin',token:drag.token,kind});move(e);}
 function move(e){if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();pending=point(e);if(!raf)raf=requestAnimationFrame(flush);}
 function finish(e){if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();e.stopImmediatePropagation();pending=point(e);flush();const current=drag,inside=point(e).inside;drag=null;root.classList.remove('dragging');send({phase:inside?'drop':'cancel',token:current.token});if(inside)dropped++;else cancelled++;if(current.card.hasPointerCapture(current.pointerId))current.card.releasePointerCapture(current.pointerId);}
 function cancel(){if(!drag)return;const current=drag;drag=null;pending=null;cancelAnimationFrame(raf);raf=0;root.classList.remove('dragging');send({phase:'cancel',token:current.token});cancelled++;if(current.card.hasPointerCapture(current.pointerId))current.card.releasePointerCapture(current.pointerId);status.textContent='설치를 취소했습니다.';}
 const rotate=()=>{angle=(angle+Math.PI/4)%(Math.PI*2);if(drag)send({phase:'rotate',token:drag.token,angle});};
 root.querySelector('#placementRotate').onclick=rotate;root.querySelector('.placement-heading button').onclick=()=>{cancel();root.hidden=true;onClose();};
 root.querySelector('input[type="search"]').oninput=e=>{for(const b of cards.children)b.hidden=!b.dataset.label.includes(e.target.value.trim());};
 window.addEventListener('pointermove',move,true);window.addEventListener('pointerup',finish,true);window.addEventListener('pointercancel',cancel,true);root.addEventListener('lostpointercapture',cancel,true);window.addEventListener('blur',cancel);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancel();});
 window.addEventListener('keydown',e=>{if(root.hidden)return;if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(drag)cancel();else{root.hidden=true;onClose();}}else if(drag&&e.code==='KeyR'){e.preventDefault();e.stopImmediatePropagation();rotate();}},true);
 return {ack(result){if(result.requestId?.includes(':place:')){status.textContent=result.accepted?'물건을 설치했습니다.':result.reason;lastResult={...lastResult,ack:result};}},open(){cancel();root.hidden=false;onOpen();},hide(){cancel();root.hidden=true;},update(value){lastResult=value;status.textContent=value.reason||'가까운 지지면 위에 설치할 수 있습니다.';status.dataset.valid=String(!!value.valid);},diagnostics:()=>({open:!root.hidden,dragging:!!drag,dropped,cancelled,lastResult})};
}
