import {validatePresentationView} from './presentation-view.mjs';
import {getDocument,GlobalWorkerOptions} from './pdf.mjs';
import {sha,validAttachment} from './save-v2.mjs';
GlobalWorkerOptions.workerSrc=new URL('./pdf.worker.mjs',import.meta.url).href;
const encode=a=>{let s='';for(const v of a)s+=String.fromCharCode(v);return btoa(s)};const decode=s=>Uint8Array.from(atob(s),v=>v.charCodeAt(0));
export function createPresentation({send,identity,isHost,members,inWorld,inWorldPointer,notify,mount,scopeId=""}){
 const root=document.createElement('div');root.id=scopeId?scopeId+'-presentation':'presentation';root.hidden=true;(mount||document.querySelector('.tool-panel')).append(root);
 root.innerHTML=`<p>PDF 또는 PNG/JPEG를 올리세요. PPTX는 PowerPoint에서 PDF로 내보낸 뒤 사용합니다.</p><div class="row"><input id="slideUpload" type="file" accept="application/pdf,image/png,image/jpeg" multiple><select id="slideFiles"></select><button id="slidePrev">이전</button><button id="slideNext">다음</button><span id="slidePage"></span></div><div class="row"><select id="presenterSelect"></select><button id="assignPresenter">발표자 인계 (방장)</button><button id="slideCancel">자료 전송 취소</button><button id="slideRetry">자료 다시 요청</button></div><div class="row"><label>발표 도구 <select id="slideTool"><option value="laser">레이저</option><option value="pen">주석 펜</option></select></label><select id="slideInk"><option value="#c94c36">빨강</option><option value="#315eac">파랑</option><option value="#2b7258">초록</option></select><button id="slideUndo">현재 쪽 주석 되돌리기</button></div><canvas id="slideCanvas" width="1280" height="720"></canvas><p id="slideStatus">자료 없음 · 사용자 자료는 공간 파일에 포함됩니다.</p>`;
 if(scopeId)for(const el of root.querySelectorAll('[id]')){el.dataset.control=el.id;el.id=scopeId+'-'+el.id;}const $=id=>root.querySelector(scopeId?'[data-control="'+id+'"]':'#'+id);const attachments=new Map(),pending=new Map();let metas=[],presenter='',selected=0,page=1,pageCount=1,pdf=null,pdfId='',renderId=0,cancelled=false;
 let pageRevision=0;let annotations=[],drawing=null,laserAt=0,lastPointer=null,pointerSequence=0,lastPointerSequence=-1,pointerTimer;const base=document.createElement('canvas');base.width=1280;base.height=720;
 const view=()=>({selected,page,annotations:structuredClone(annotations)});
 function paint(){const c=$('slideCanvas').getContext('2d');c.drawImage(base,0,0);for(const stroke of [...annotations.filter(s=>s.asset===metas[selected]?.id&&s.page===page),...(drawing?[drawing]:[])]){c.strokeStyle=stroke.color;c.lineWidth=4;c.lineCap='round';c.beginPath();stroke.points.forEach((p,i)=>i?c.lineTo(p[0]*1280,p[1]*720):c.moveTo(p[0]*1280,p[1]*720));c.stroke()}}
 function pointer(uv){clearTimeout(pointerTimer);if(uv)pointerTimer=setTimeout(()=>pointer(null),400);lastPointer=uv;inWorldPointer?.(uv);paint();if(uv){const c=$('slideCanvas').getContext('2d');c.fillStyle='#f33225';c.beginPath();c.arc(uv[0]*1280,uv[1]*720,7,0,Math.PI*2);c.fill()}}
 function change(m){if(m.type==='presentation-pointer'){m.asset=metas[selected]?.id||'';m.page=page;m.sequence=++pointerSequence;m.pageRevision=pageRevision;}if(isHost())receive(identity(),m);else send(m)}
 const uv=e=>{const r=$('slideCanvas').getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]};
 $('slideCanvas').onpointerdown=e=>{if(!permitted(identity())||!metas[selected])return;if($('slideTool').value==='pen'){drawing={id:crypto.randomUUID(),asset:metas[selected].id,page,color:$('slideInk').value,points:[uv(e)]};$('slideCanvas').setPointerCapture(e.pointerId)}};
 $('slideCanvas').onpointermove=e=>{if(!permitted(identity()))return;if(drawing){if(drawing.points.length<128)drawing.points.push(uv(e));paint()}else if($('slideTool').value==='laser'&&performance.now()-laserAt>80){laserAt=performance.now();change({type:'presentation-pointer',uv:uv(e)})}};
 $('slideCanvas').onpointerup=()=>{if(drawing){if(drawing.points.length>1)change({type:'presentation-ink',stroke:drawing});drawing=null;paint()}};
 $('slideCanvas').onpointerleave=()=>{if(permitted(identity()))change({type:'presentation-pointer',uv:null})};
 $('slideUndo').onclick=()=>change({type:'presentation-undo'});
 const permitted=who=>who===(presenter||members()?.[0]?.id)||isHost()&&who===identity();
 function open(){root.hidden=false;const list=$('presenterSelect');list.replaceChildren();for(const m of members()||[])list.append(new Option(m.id===identity()?'나':m.id.slice(-6),m.id));list.value=presenter||members()?.[0]?.id||'';render()}
 function updateSelect(){const list=$('slideFiles');list.replaceChildren();for(let i=0;i<metas.length;i++)list.append(new Option(metas[i].name,i));list.value=String(selected)}
 async function render(){const token=++renderId;const a=metas[selected];if(!a){$('slideStatus').textContent='자료 없음';return}const data=attachments.get(a.id);if(!data){$('slideStatus').textContent='자료 수신 중…';return}const canvas=$('slideCanvas'),ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);
  try{if(a.mime==='application/pdf'){if(pdfId!==a.id){await pdf?.destroy();pdf=await getDocument({data:data.slice(),isEvalSupported:false,disableFontFace:false}).promise;pdfId=a.id}pageCount=Math.min(200,pdf.numPages);page=Math.min(page,pageCount);const p=await pdf.getPage(page);const original=p.getViewport({scale:1}),scale=Math.min(1280/original.width,720/original.height),viewport=p.getViewport({scale});const off=document.createElement('canvas');off.width=Math.ceil(viewport.width);off.height=Math.ceil(viewport.height);await p.render({canvasContext:off.getContext('2d'),viewport}).promise;if(token!==renderId)return;ctx.drawImage(off,(1280-off.width)/2,(720-off.height)/2)}else{pageCount=1;const bitmap=await createImageBitmap(new Blob([data],{type:a.mime}));if(bitmap.width>8192||bitmap.height>8192){bitmap.close();throw Error('이미지 크기 제한 8192px')}const scale=Math.min(1280/bitmap.width,720/bitmap.height);ctx.drawImage(bitmap,(1280-bitmap.width*scale)/2,(720-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close()}
   $('slidePage').textContent=`${page} / ${pageCount}`;$('slideStatus').textContent=a.name+' · '+Math.round(a.bytes/1024)+' KB · '+(permitted(identity())?'발표 권한 있음':'관람');base.getContext('2d').clearRect(0,0,1280,720);base.getContext('2d').drawImage(canvas,0,0);paint();inWorld(canvas.toDataURL('image/jpeg',.80).split(',')[1]);
  }catch(e){notify('발표 자료 렌더링 실패: '+e.message)}
 }
 async function transfer(a,to=''){const data=attachments.get(a.id);if(!data)return;send({type:'asset-begin',asset:a,total:Math.ceil(data.length/12288)},to);for(let offset=0,i=0;offset<data.length;offset+=12288,i++){if(cancelled)return;send({type:'asset-chunk',id:a.id,index:i,data:encode(data.subarray(offset,offset+12288))},to);await new Promise(r=>setTimeout(r,30))}send({type:'asset-end',id:a.id},to)}
 function broadcastState(to=''){send({type:'presentation-state',metas,selected,page,presenter:presenter||members()?.[0]?.id||identity(),pageRevision,view:view()},to)}
 async function receive(sender,m){
  if(['presentation-pointer','presentation-ink','presentation-undo'].includes(m.type)){
   if(isHost()&&!permitted(sender))return true;
   if(m.type==='presentation-pointer'){if(m.pageRevision!==pageRevision||m.asset!==(metas[selected]?.id||'')||m.page!==page||!Number.isSafeInteger(m.sequence))return true;if(!isHost()&&m.sequence<=lastPointerSequence)return true;if(isHost())m.sequence=++pointerSequence;lastPointerSequence=m.sequence;if(m.uv!==null&&(!Array.isArray(m.uv)||m.uv.length!==2||m.uv.some(n=>!Number.isFinite(n)||n<0||n>1)))return true;pointer(m.uv);if(isHost())send(m);return true}
   if(!isHost())return true;
   if(m.type==='presentation-ink'){try{validatePresentationView({selected,page,annotations:[...annotations,m.stroke]},metas);annotations.push(m.stroke)}catch{return true}}
   else{const at=annotations.findLastIndex(s=>s.asset===metas[selected]?.id&&s.page===page);if(at>=0)annotations.splice(at,1)}broadcastState();render();return true;
  }
  if(m.type==='asset-request'){if(isHost()){for(const a of metas)transfer(a,sender);broadcastState(sender)}return true}
  if(m.type==='presentation-request'){if(isHost()&&permitted(sender)){pageRevision++;pointer(null);selected=Math.max(0,Math.min(metas.length-1,Number(m.selected)||0));page=Math.max(1,Math.min(200,Number(m.page)||1));broadcastState();render()}return true}
  if(m.type==='presentation-state'){if(isHost())return true;if(!Array.isArray(m.metas)||m.metas.length>64)return true;let v;try{v=validatePresentationView(m.view||{selected:m.selected,page:m.page,annotations:[]},m.metas)}catch{return true}if(!Number.isSafeInteger(m.pageRevision)||m.pageRevision<pageRevision)return true;pageRevision=m.pageRevision;metas=m.metas;if(selected!==v.selected||page!==v.page)pointer(null);selected=v.selected;page=v.page;annotations=v.annotations;presenter=m.presenter;updateSelect();render();return true}
  if(isHost()&&!permitted(sender))return true;
  if(m.type==='asset-begin'){const a=m.asset;if(!a||!['application/pdf','image/png','image/jpeg'].includes(a.mime)||!/^[a-f0-9]{64}$/.test(a.id)||a.sha256!==a.id||typeof a.name!=='string'||a.name.length>160||a.bytes>16*1024*1024||a.bytes<1||m.total!==Math.ceil(a.bytes/12288)||pending.size>=2)return true;pending.set(a.id,{a,total:m.total,chunks:new Map(),at:Date.now()});return true}
  if(m.type==='asset-chunk'){const p=pending.get(m.id);if(!p||!Number.isSafeInteger(m.index)||m.index<0||m.index>=p.total||typeof m.data!=='string'||m.data.length>16384||p.chunks.has(m.index))return true;try{p.chunks.set(m.index,decode(m.data))}catch{}return true}
  if(m.type==='asset-end'){const p=pending.get(m.id);if(!p||p.chunks.size!==p.total)return true;const data=new Uint8Array(p.a.bytes);let offset=0;for(let i=0;i<p.total;i++){const b=p.chunks.get(i);if(offset+b.length>data.length){pending.delete(m.id);return true}data.set(b,offset);offset+=b.length}try{validAttachment(p.a,data);if(offset!==data.length||await sha(data)!==p.a.sha256)throw Error('checksum');attachments.set(m.id,data);if(!metas.some(a=>a.id===m.id)){metas.push(p.a);if(isHost())pageRevision++;}if(isHost()){for(const who of members()||[])if(who.id!==identity()&&who.id!==sender)transfer(p.a,who.id);broadcastState()}updateSelect();render()}catch(e){notify('자료 검증 실패: '+e.message)}pending.delete(m.id);return true}return false
 }
 $('slideUpload').onchange=async e=>{if(!permitted(identity())){notify('현재 발표자만 자료를 올릴 수 있습니다');return}cancelled=false;for(const file of e.target.files){if(file.size>16*1024*1024||metas.length>=64){notify('자료당 16MB, 최대 64개입니다');continue}const data=new Uint8Array(await file.arrayBuffer()),id=await sha(data),a={id,sha256:id,name:file.name.slice(0,160),mime:file.type,bytes:data.length};try{validAttachment(a,data);attachments.set(id,data);if(!metas.some(m=>m.id===id))metas.push(a);await transfer(a);if(isHost()){pageRevision++;broadcastState()}updateSelect();render()}catch(e){notify(e.message)}}e.target.value=''};
 function select(index,n){if(!permitted(identity()))return notify('현재 발표자가 페이지를 넘길 수 있습니다');if(isHost()){pageRevision++;pointer(null);selected=index;page=n;broadcastState();render()}else send({type:'presentation-request',selected:index,page:n})}
 $('slideFiles').onchange=()=>select(Number($('slideFiles').value),1);$('slidePrev').onclick=()=>select(selected,Math.max(1,page-1));$('slideNext').onclick=()=>select(selected,Math.min(pageCount,page+1));
 $('assignPresenter').onclick=()=>{if(isHost()){presenter=$('presenterSelect').value;pageRevision++;pointer(null);broadcastState();render()}};$('slideCancel').onclick=()=>{cancelled=true;pending.clear();notify('자료 전송을 취소했습니다')};$('slideRetry').onclick=()=>{cancelled=false;send({type:'asset-request'})};
 const cleanup=setInterval(()=>{for(const[id,p]of pending)if(Date.now()-p.at>120000)pending.delete(id)},10000);
 async function validate(list,files){for(const a of list||[]){const data=files.get(a.id);if(!data)throw Error('누락된 발표 자료');validAttachment(a,data);if(a.mime==='application/pdf'){const task=getDocument({data:data.slice(),isEvalSupported:false});try{const document=await task.promise;if(document.numPages>200)throw Error('PDF는 200쪽까지 지원합니다');await document.getPage(1)}finally{await task.destroy()}}else{const b=await createImageBitmap(new Blob([data],{type:a.mime}));const okay=b.width<=8192&&b.height<=8192;b.close();if(!okay)throw Error('이미지 크기 제한 8192px')}}return true}
 return {root,physicalPointer(actor,uv){if(isHost()&&permitted(actor))change({type:"presentation-pointer",uv})},open,validate,diagnostics:()=>({view:view(),pageRevision,presenter,pointer:lastPointer,assets:metas.map(a=>({id:a.id,name:a.name,ready:attachments.has(a.id)}))}),ready(){return metas.every(a=>attachments.has(a.id))},view,session(){return {...view(),presenter,pageRevision}},setSession(s){pageRevision=s.pageRevision||0;lastPointerSequence=-1;pointer(null);selected=s.selected||0;page=s.page||1;annotations=structuredClone(s.annotations||[]);presenter=s.presenter||'';updateSelect();render()},hide(){root.hidden=true},receive,sync(who){broadcastState(who);for(const a of metas)transfer(a,who)},attachments,metadata(){return structuredClone(metas)},restore(list,files,savedView={selected:0,page:1,annotations:[]}){cancelled=true;pageRevision=0;lastPointerSequence=-1;pointer(null);pending.clear();attachments.clear();for(const[k,v]of files)attachments.set(k,v);metas=structuredClone(list||[]);const v=validatePresentationView(savedView,metas);selected=v.selected;page=v.page;annotations=v.annotations;presenter='';updateSelect();render();cancelled=false},destroy(){cancelled=true;clearInterval(cleanup);pdf?.destroy();root.remove()}};
}
