export function createSocial({send,isHost,id,scope,pause,resume,notify,profile}){
 const entry=document.querySelector('#entry .welcome');const label=document.createElement('label');label.textContent='집에서 사용할 이름 ';const name=document.createElement('input');name.id='displayName';name.maxLength=24;name.placeholder='이름';try{name.value=localStorage.getItem('moyeo-name')||'친구'}catch{name.value='친구'}label.append(name);entry.insertBefore(label,entry.querySelector('.buttons'));
 name.onchange=()=>{try{localStorage.setItem('moyeo-name',name.value)}catch{}profile(name.value)};
 const panel=document.createElement('section');panel.id='textChat';panel.hidden=true;panel.innerHTML='<div class="row"><strong>텍스트 대화</strong><button id="closeChat">닫기</button></div><p class="fine">선택한 근거리 / 현재 방 / 승인된 전체 방송 범위로 전달합니다. 대화는 공간 파일에 저장하지 않습니다.</p><div id="chatLines" role="log"></div><form id="chatForm"><input id="chatText" maxlength="400" placeholder="한글로 대화하기" autocomplete="off"><button>보내기</button></form>';document.body.append(panel);
 const button=document.createElement('button');button.textContent='대화 · Enter';button.onclick=open;document.getElementById('topbar').append(button);const $=id=>panel.querySelector('#'+id);let rows=[];const limits=new Map();
 function open(){if(!id())return;pause();panel.hidden=false;$('chatText').focus()}function close(){panel.hidden=true;resume()}
 function display(m){rows.push(m);rows=rows.slice(-40);$('chatLines').replaceChildren();for(const line of rows){const p=document.createElement('p');p.textContent=line.name+' · '+line.text;$('chatLines').append(p)}$('chatLines').scrollTop=$('chatLines').scrollHeight}
 function receive(sender,m){if(m.type!=='chat')return false;if(typeof m.text!=='string'||m.text.length>400||!m.text.trim())return true;if(isHost()){if(performance.now()-(limits.get(sender)||-9999)<500)return true;limits.set(sender,performance.now());const out={type:'chat',speaker:sender,name:profile(null,sender),text:m.text.trim()};if(sender===id()||scope(sender,id()))display(out);send(out,'relay',sender)}else if(scope(m.speaker,id())||m.speaker===id())display(m);return true}
 $('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatText').value.trim();if(!text)return;if(isHost())receive(id(),{type:'chat',text});else send({type:'chat',text});$('chatText').value='';$('chatText').focus()};$('closeChat').onclick=close;
 document.addEventListener('keydown',e=>{if(e.code==='Enter'&&panel.hidden&&e.target===document.getElementById('canvas')){e.preventDefault();open()}else if(e.code==='Escape'&&!panel.hidden){e.preventDefault();e.stopImmediatePropagation();close()}},true);
 return {receive,name:()=>name.value.trim().slice(0,24)||'친구',hide(){panel.hidden=true}};
}
