import {chromium} from 'playwright';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const url='https://mjayj9.github.io/Friendslop_HomeOffice/',browsers=[],pages=[],results=[],errors=[],resources=[],promises=[];const pass=name=>{results.push({name,passed:true});console.log('PASS',name)};const wait=(p,f,t=65000)=>p.waitForFunction(f,null,{polling:100,timeout:t});const d=p=>p.evaluate(()=>Homeoffice.diagnostics());
try{
 for(let i=0;i<2;i++){const b=await chromium.launch({headless:true,args:['--use-angle=d3d11','--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});browsers.push(b);const p=await b.newPage({viewport:i?{width:1280,height:720}:{width:1920,height:1080},permissions:['microphone']});pages.push(p);p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());if(!i&&/index\.(wasm|pck)$/.test(r.url()))resources.push({url:r.url(),mime:r.headers()['content-type']})});await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await wait(p,()=>window.Homeoffice?.readyState());assert.equal(await p.evaluate(()=>isSecureContext),true);if(!i){await p.locator('#host').click({force:true});await wait(p,()=>Homeoffice.diagnostics().host&&Homeoffice.diagnostics().currentState?.players.length===1);pass('Public GitHub Pages Godot WASM/PCK initializes in HTTPS secure context')}else{await p.locator('#room').fill((await d(pages[0])).room);await p.locator('#join').click({force:true});await wait(p,()=>Homeoffice.diagnostics().currentState?.players.length===2)}}
 const[a,b]=pages;await wait(a,()=>Homeoffice.diagnostics().currentState?.players.length===2);pass('Actual public PeerServer signaling joins two independent Chromium browsers');const me=(await d(b)).id,before=(await d(a)).currentState.players.find(p=>p.id===me).p;await b.keyboard.down('KeyW');await b.waitForTimeout(700);await b.keyboard.up('KeyW');await b.waitForTimeout(700);assert.ok(Math.hypot(...(await d(a)).currentState.players.find(p=>p.id===me).p.map((n,i)=>n-before[i]))>.6);pass('Public build shares authoritative character movement');
 await a.keyboard.press('Enter');await a.locator('#chatText').fill('안녕하세요. 같은 집에서 만났어요.');await a.locator('#chatText').press('Enter');await wait(b,()=>document.getElementById('chatLines').textContent.includes('같은 집에서 만났어요'));pass('Public build relays Korean text chat to the nearby participant');await a.locator('#closeChat').click({force:true});
 await a.keyboard.press('Escape');await a.locator('#mic').click({force:true});await a.locator('#openMic').check({force:true});await wait(b,()=>Homeoffice.diagnostics().voiceIncoming===1);await b.waitForTimeout(1800);const stats=await b.evaluate(()=>Homeoffice.voice_stats());assert.ok(stats.some(s=>s.packetsReceived>0));pass('HTTPS public build carries actual RTC audio packets from synthetic microphone');await a.locator('#micOff').click({force:true});await a.locator('#resume').click({force:true});await a.screenshot({path:'homeoffice/evidence/v2-pages-game.png'});
 await Promise.all(promises);const manifest=JSON.parse(await fs.readFile('homeoffice/docs/v2/web-build-manifest.json'));for(const r of resources){const response=await fetch(r.url);assert.equal(response.ok,true);const bytes=Buffer.from(await response.arrayBuffer());r.bytes=bytes.length;r.sha256=crypto.createHash('sha256').update(bytes).digest('hex');const expected=manifest.files.find(f=>url+f.file===r.url);assert.equal(r.sha256,expected.sha256)}pass('Public WASM and PCK hashes match the reviewed build');
 const hardware=await a.evaluate(()=>{const c=document.getElementById('canvas').getContext('webgl2');const e=c?.getExtension('WEBGL_debug_renderer_info');return {userAgent:navigator.userAgent,renderer:e?c.getParameter(e.UNMASKED_RENDERER_WEBGL):'not exposed',hardwareConcurrency:navigator.hardwareConcurrency}});results.push({name:'observed hardware and FPS',informational:true,hardware,performance:(await d(a)).performance});
}catch(e){results.push({name:'public integration',passed:false,error:e.stack});console.log('FAIL',e.stack);for(const[i,p]of pages.entries())try{await p.screenshot({path:`homeoffice/evidence/v2-pages-failure-${i}.png`});console.log('STATUS',i,await p.locator('#loading').textContent(),await p.locator('#status').textContent())}catch{}}finally{await Promise.allSettled(promises);await fs.writeFile('homeoffice/evidence/pages-validation.json',JSON.stringify({url,time:new Date().toISOString(),environment:'Actual GitHub Pages HTTPS URL, public PeerServer/STUN, two independent Chromium processes on one Windows PC. Same-device P2P; not separate WAN PCs, not human microphone quality.',results,resources,errors},null,2));for(const b of browsers)try{await b.close()}catch{}}
if(results.some(r=>r.passed===false))process.exitCode=1;
