import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,randomInt,randomUUID} from 'node:crypto';
import {createAdminPolicy,memoryStore,ROOM_IDS} from '../server/admin-policy.mjs';
import {createPolicyVerifier} from '../web/room-policy.mjs';
import {createPolicyHttpServer} from '../server/serve-admin.mjs';
const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),publicKey=pair.publicKey.export({format:'jwk'});
async function fixture(){const pin=String(randomInt(100000,1000000)),adminToken=randomUUID(),store=memoryStore();let now=Date.now();const policy=createAdminPolicy({verifyIdentity:async token=>({id:token===adminToken?'operator':'student'}),adminIds:new Set(['operator']),privateKey:pair.privateKey,store,now:()=>now});await policy.bootstrap(pin);return {pin,adminToken,policy,store,advance:ms=>now+=ms,verifier:createPolicyVerifier({publicKey,clock:()=>now}),command:extra=>policy.command({token:adminToken,session:'test-session',challenge:randomUUID(),zone:'meeting',operation:'lock',pin,revision:0,...extra})};}
test('Student host / URL role / asserted administrator cannot unlock; authenticated operator changes one room',async()=>{const f=await fixture();await assert.rejects(f.command({token:'student-isHost-admin=true'}),e=>e.status===403);const challenge=randomUUID(),packet=await f.command({challenge});const p=await f.verifier.accept(packet,{expectedSession:'test-session',challenge});assert.equal(p.rooms.meeting.locked,true);assert.equal(p.rooms.living.locked,false);assert.equal(Object.keys(p.rooms).length,ROOM_IDS.length);assert.ok(!JSON.stringify(packet).includes(f.pin));assert.equal('hall' in p.rooms,false);});
test('Wrong PIN attempt budget is shared across rooms; correct PIN cannot bypass lockout',async()=>{const f=await fixture(),wrong=f.pin==='100000'?'100001':'100000';for(let i=0;i<5;i++)await assert.rejects(f.command({pin:wrong,zone:i%2?'living':'meeting'}),e=>e.status===403);await assert.rejects(f.command({}),e=>e.status===429);f.advance(900001);await f.command({});});
test('Nonce replay, stale revision, signature mutation, cross-session and expiry are rejected',async()=>{const f=await fixture(),challenge=randomUUID(),packet=await f.command({challenge});await f.verifier.accept(packet,{expectedSession:'test-session',challenge});await assert.rejects(f.command({challenge,revision:1}),e=>e.status===409);await assert.rejects(f.command({revision:0}),e=>e.status===409);await assert.rejects(f.verifier.accept(packet,{expectedSession:'other-session',challenge}));await assert.rejects(f.verifier.accept({...packet,payload:packet.payload.slice(0,-3)+'abc'},{expectedSession:'test-session',challenge}));await assert.rejects(f.verifier.accept(packet,{expectedSession:'test-session',challenge:randomUUID()}));f.advance(30001);await assert.rejects(f.verifier.accept(packet,{expectedSession:'test-session',challenge}));});
test('Independent salted room PIN change persists privately; public state and stale world cannot replace it',async()=>{const f=await fixture(),newPin=String(randomInt(1000000,10000000));await f.command({operation:'set-pin',newPin});await assert.rejects(f.command({revision:1}),e=>e.status===403);await f.command({pin:newPin,revision:1,operation:'unlock'});const data=await f.store.read();assert.notDeepEqual(data.rooms.meeting,data.rooms.living);assert.ok(!JSON.stringify(data).includes(f.pin));assert.ok(!JSON.stringify(data).includes(newPin));await assert.rejects(f.command({zone:'hall',revision:2}),e=>e.status===400);});
test('Broadcast authorization binds the authenticated operator to a session actor and expires',async()=>{const f=await fixture(),challenge=randomUUID(),packet=await f.command({zone:'utility',operation:'broadcast-authorize',actor:'peer-operator',challenge});const p=await f.verifier.accept(packet,{expectedSession:'test-session',challenge});assert.ok(p.broadcasters['peer-operator']);assert.equal(p.broadcasters['student-host'],undefined);f.advance(600001);const nonce=randomUUID(),state=await f.policy.state({session:'test-session',challenge:nonce});assert.deepEqual((await f.verifier.accept(state,{expectedSession:'test-session',challenge:nonce})).broadcasters,{});});
test('HTTP rejects foreign origins, emits no credentials, and verifies signed state through an actual socket',async()=>{const f=await fixture(),server=createPolicyHttpServer({policy:f.policy,origins:['http://localhost:8065']});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const url='http://127.0.0.1:'+server.address().port,challenge=randomUUID();assert.equal((await fetch(url+'/state')).status,403);const r=await fetch(url+'/state?'+new URLSearchParams({session:'test-session',challenge}),{headers:{Origin:'http://localhost:8065'}});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');const p=await f.verifier.accept(await r.json(),{expectedSession:'test-session',challenge});assert.equal(p.rooms.meeting.locked,false);const denied=await fetch(url+'/command',{method:'POST',headers:{Origin:'http://localhost:8065','Content-Type':'application/json',Authorization:'Bearer student'},body:JSON.stringify({session:'test-session',challenge,zone:'meeting',pin:f.pin,revision:0,operation:'lock'})});assert.equal(denied.status,403);assert.ok(!(await denied.text()).includes(f.pin));}finally{await new Promise(r=>server.close(r));}});
