"""Reviewable V5 spatial design. Does not silently change the live V4 layout."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
out=R/'docs/v5';out.mkdir(exist_ok=True)
rooms=[]
def room(id,name,wing,rect,y=0,uses='',door=None,windows='outer wall',finish=''):
    rooms.append(dict(id=id,name=name,wing=wing,rect=rect,y=y,uses=uses,door=door,windows=windows,finish=finish))
room('arrival','도착 로비 / 교실','PUBLIC',[-5,12,5,19],uses='안내 데스크·대기 4석·교실 입장 콘솔·초대/연결 정보',door=[0,19],finish='밝은 석재, 부드러운 흡음 천장')
room('home-link','HOME 연결 갤러리','PUBLIC',[-8,10,-5,14],uses='비를 피하는 보행·테라스 연결',door=[-8,12],finish='석재와 목재 전환')
room('office-link','OFFICE 연결 갤러리','PUBLIC',[5,10,8,14],uses='방문자 분기·회의 안내',door=[8,12])
room('courtyard','중정·공용 휴게','PUBLIC',[-8,-8,8,10],uses='벤치·식재·햇빛·주변 보행, 코트 관람 경계 외부',finish='외부 석재, 잔디, 목재 벤치')
room('home-entry','HOME 현관','HOME',[-18,10,-8,15],uses='신발장·외투 수납·벤치·계단 진입',door=[-8,12],finish='참나무·직물, 따뜻한 조명')
room('home-hall','HOME 공용 복도','HOME',[-18,-13,-14,10],uses='개인실을 통과하지 않는 화장실·계단 접근',finish='목재 바닥·흡음 러너')
room('living','거실','HOME',[-28,6,-18,15],uses='소파 3개·낮은 테이블·책·독서등·테라스 문',door=[-18,8],finish='목재·직물·차분한 조명')
room('dining','식당','HOME',[-28,0,-18,6],uses='지지대 있는 식탁·8개 의자·접시·음식, 주방과 거실에 직접 연결',door=[-18,3])
room('kitchen','주방','HOME',[-28,-7,-18,0],uses='냉장→세척→준비→조리→담기, 작업대 앞 1.4m 이상 여유',door=[-18,-3],finish='무광 타일·석재 상판·목재 수납')
room('pantry','팬트리','HOME',[-28,-9,-18,-7],uses='식재료·냉장 보조·깊이 0.45m 선반',door=[-23,-7])
room('home-service','세탁·다용도','HOME',[-28,-13,-18,-9],uses='세탁/건조대·청소 수납·린넨 준비·생활 물품 보관',door=[-18,-11])
room('bath_home_ground','HOME 공용 화장실','HOME',[-14,1.5,-8,4],uses='차폐 전실·변기 칸·세면·거울·수건·환기, 식당에 직접 열리지 않음',door=[-14,2.75],finish='작은 타일·무광 도기·습식 배수 구역')
room('home-stair','HOME U 계단','HOME',[-13.9,5.1,-10.4,10],uses='20단×0.18m=3.6m, 폭1.5m, 디딤판0.30m, 계단참1.5m',door=[-12.8,10],finish='목재 디딤판·불투명 챌판·손잡이')
room('upper-hall','HOME 2층 공용 복도','HOME',[-18,-13,-14,15],3.6,'욕실·옷방·독서실을 침실 통과 없이 연결',finish='흡음 러너·발밑 조명')
room('upper-landing','HOME 2층 계단참','HOME',[-14,10,-8,15],3.6,'U 계단 개구부와 연결, 난간·문 충돌 없는 출구',door=[-12.8,10])
room('sleep','공동 수면실','HOME',[-28,-13,-18,-5],3.6,'원래 침대 ID·좌석 점유 보존, 침대·협탁·독서등·수납',door=[-18,-9])
room('sleep-private','1인 수면실','HOME',[-28,-5,-22,1],3.6,'침대·협탁·수납, 옆 공용 복도로 독립 출입',door=[-22,-4.2])
room('sleep-lobby','침실 앞 공용 분기·린넨 수납','HOME',[-22,-5,-18,1],3.6,'1인 수면실과 복도 연결, 다른 침실 통과 없음',door=[-18,-2])
room('bath_upper','2층 욕실·린넨','HOME',[-14,1.5,-8,4],3.6,'아래층 위생 블록 위에 변기·세면·샤워·수건·분리 수납',door=[-14,2.75],finish='타일·습식 차폐·간접 조명')
room('wardrobe','의상방','HOME',[-28,1,-18,6],3.6,'옷장·전신 거울·꾸미기 콘솔·피팅 공간, 실제 클릭으로만 시작',door=[-18,3.5])
room('reading','독서·휴게','HOME',[-28,6,-18,15],3.6,'기존 소파·낮은 책상·책 ID 유지, 서가·창가 좌석',door=[-18,10])
room('reception','OFFICE 리셉션·대기','OFFICE',[8,10,20,15],uses='방문자 응대·안내 데스크·대기·회의 예약 표시',door=[8,12],finish='석재·천 패널·분명한 안내')
room('office-hall','OFFICE 중앙 홀','OFFICE',[20,-18,24,15],uses='회의·업무·위생·계단 분기, 공용 통로 폭4m',finish='흡음 카펫·간접 조명')
room('meeting','주회의실','OFFICE',[8,2,20,10],uses='8–12석 가구, 실제 지원8명과 구분; 스크린·보드·레이저·원본 협업',door=[20,6],windows='서쪽 창+차광, 화면 정면 창 금지',finish='흡음 천장·패브릭·무광 목재')
room('resources','자료·브레인스토밍','OFFICE',[8,-4,14,2],uses='자료 원본·문서 선반·브레인스토밍·마인드맵, 회의실 직접 연결',door=[11,2])
room('bath_ground','OFFICE 공용 화장실','OFFICE',[14,-4,20,1],uses='공용 홀에서 바로 접근; 변기 칸막이·세면·거울·물내림·환기',door=[20,-1.5],finish='타일·무광 도기')
room('service-hall','자료·지원 연결 복도','OFFICE',[8,-6,20,-4],uses='자료실 독립 출입·청소/지원실 진입',door=[20,-5])
room('shared-work','공동 업무실','OFFICE',[24,0,36,9],uses='지지대 책상·모니터·수납·근거리 대화·문서 작업',door=[24,4.5],finish='카펫·눈부심 억제 조명')
room('small-meeting-a','소회의실 A','OFFICE',[24,-4,29,0],uses='4석 테이블·보드·자료',door=[26.5,-4])
room('small-meeting-b','소회의실 B','OFFICE',[29,-4,34,0],uses='4석 테이블·보드·자료',door=[31.5,-4])
room('work-cross-hall','업무 지원 복도','OFFICE',[24,-6,40,-4],uses='두 소회의실 독립 접근·IT 수납',door=[24,-5])
room('phone-a','전화·집중 부스','OFFICE',[36,0,38.5,2.5],uses='문·좌석·작업판·방별 음성 감쇠, 암호학적 비밀 보장은 별도',door=[36,1.25],finish='흡음 패널·기계 환기')
room('print','인쇄·자료 보관','OFFICE',[36,3,40,7],uses='문서 선반·프린터 모형·내보내기 콘솔, 유료 인쇄 자동 실행 없음',door=[36,5])
room('it-store','IT·관리 수납','OFFICE',[36,-9,40,-6],uses='기기·케이블·소모품 수납',door=[38,-6])
room('office-pantry','OFFICE 팬트리','OFFICE',[24,9,29,13],uses='싱크·냉장·컵·준비대·정리',door=[24,11],finish='타일·목재 수납')
room('office-lounge','업무 휴게','OFFICE',[29,9,36,13],uses='휴게 좌석·음료, 업무실과 연결',door=[32.5,9])
room('broadcast','방송실','OFFICE',[8,-13,14,-8],uses='콘솔·마이크·ON AIR·한국어 자막·공지',door=[14,-11],finish='흡음·부유 바닥 표현·소음 큰 공간과 분리')
room('broadcast-airlock','방송 전실','OFFICE',[14,-13,17,-10],uses='두 문·소리 감쇠·송출 준비',door=[17,-11.5])
room('broadcast-service','방송·지원 복도','OFFICE',[17,-14,20,-6],uses='방송 전실과 중앙 홀 연결',door=[20,-10])
room('cleaning','청소·지원 수납','OFFICE',[8,-8,14,-6],uses='청소 도구·보관 선반',door=[11,-6])
room('office-stair','OFFICE U 계단','OFFICE',[24,-12,27.5,-7.1],uses='20단×0.18m, 상부 개인실 복도에 실제 연결',door=[25,-7.1])
room('office-upper-hall','개인실 연결 홀','OFFICE',[20,-18,24,0],3.6,'2층 화장실·계단·확장 개인실 복도 연결',door=[24,-7])
room('bath_office_upper','OFFICE 2층 화장실','OFFICE',[14,-4,20,1],3.6,'아래층 위생 블록 위에 공용 세면·변기·린넨, 개인실 통과 없음',door=[20,-1.5])
room('personal-gallery','확장 개인실 복도','OFFICE',[20,-39.6,24,-18],3.6,'기존 사용자 슬롯·문 ID 보존, 4쌍까지 예약',door=[22,-18])
for i in range(8):
    pair=i//2;z=-18-pair*5.4
    rect=[15.2,z-5.4,20,z] if i%2==0 else [24,z-5.4,28.8,z]
    room(f'office-{i+1}',f'개인실 슬롯 {i+1}','RESERVE',rect,3.6,'4.8×5.4m; 사용자 확장 시 책상·의자·수납·문과 함께 생성, 빈 예약 칸을 완성 방으로 집계하지 않음',door=[20 if i%2==0 else 24,z-2.7])
room('tactical','전술 게임 지도','PLAY',[43,-14,73,8],uses='자체 지도: 두 출발지·중앙/측면 경로·엄폐·목표·승패·다음 라운드',door=[43,3],finish='내구 바닥·식별되는 엄폐·흡음 출입 전실')
room('arcade','자유방·아케이드','PLAY',[43,8,54,16],uses='공룡 러너·관전·소품 실험·회귀 유지',door=[43,12])
room('play-link','PLAY 공용 연결','PUBLIC',[40,8,43,16],uses='OFFICE와 자유방 연결, 총 소유와 출입 권한은 무관',door=[40,13])
room('sports-view','코트 외부 관람 통로','PUBLIC',[-25,20,65,23],uses='ADMIN 경계를 넘지 않는 공개 통로·벤치',finish='외부 석재')
room('sports-airlock','관리자 출입 전실','ADMIN',[11,23,16,28],uses='실제 검증된 관리자만 통과, 열린 문·호스트·총으로 우회 불가',door=[12,23])
room('basketball','농구관','ADMIN',[-23,24,11,45],uses='28×15m 경기면 + 각3m 주변 여유; 골대·백보드·벤치·점수판',door=[11,26],finish='목재 스포츠 바닥·흡음 천장·넓은 수직 공간')
room('sports-store','운동 용품·탈의','ADMIN',[-23,45,11,52],uses='장비·볼 보관·벤치·탈의·샤워/화장실',door=[9,45],finish='내구 타일·로커')
room('football','소규모 축구장','ADMIN',[16,24,62,54],uses='40×24m 자체 소규모 경기면 + 각3m 여유; 골·네트·벤치·경계 재개',door=[16,26],finish='잔디·선·배수 경계')
room('office-stair-lobby','OFFICE 계단 진입 홀','OFFICE',[24,-7.1,28,-6],uses='중앙 공용 복도에서 계단 첫 단으로 연결',door=[24,-6.5])
room('office-upper-landing','OFFICE 2층 계단참','OFFICE',[24,-7.1,27.5,-5],3.6,'상부 계단 출구와 개인실 복도 연결',door=[24,-6])
room('east-gallery','동측 공용 갤러리','OFFICE',[36,7,40,16],uses='업무 휴게에서 자유방·전술 지도 연결',door=[36,11])
room('sports-approach','운동 구역 공개 접근로','PUBLIC',[-5,19,5,20],uses='로비에서 관람 통로로 연속 보행')
plan=dict(status='기본 설계안 / 런타임 미반영 / 완성 미술 아님',units='metres, Godot X/Z, floor Y',site=[-34,-45,78,58],rooms=rooms,stair=dict(rise=3.6,steps=20,riser=.18,tread=.30,width=1.5,landing=1.5,minimumHeadClearance=2.2,section='10단→1.8m 계단참→10단→3.6m 복도; 상부 슬래브는 전체 U 계단 개구부를 비운다'),acoustics=dict(home='목재·직물, 근거리 대화',office='흡음 카펫·회의/부스별 감쇠',sports='외부/흡음 관, 사무실과 전실 분리'),migration='Stable object IDs, saved documents, room-slot identity retained. Per-zone rigid relocation plus collision review; conflicting items must remain recoverable. No runtime migration enabled by this design file.')
(out/'architecture-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8')
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><title>COMMONS V5 공간 기본설계</title><style>body{margin:0;background:#eef0e8;color:#203934;font:15px system-ui}header{padding:22px 30px;background:#203934;color:white}h1{margin:0 0 6px;font-size:28px}main{display:grid;grid-template-columns:1fr 340px;gap:20px;padding:20px}aside{background:white;padding:20px;border-radius:14px}button{padding:10px;margin:4px;border:0;border-radius:8px;cursor:pointer}svg{background:#faf9f1;width:100%;height:74vh;border-radius:12px}rect.room{stroke:#fff;stroke-width:.18;cursor:pointer}text{pointer-events:none;fill:#203934;font-size:1.1px}p{line-height:1.65}.note{color:#7c4931}pre{white-space:pre-wrap;font:13px system-ui}a{color:#286f64}</style><header><h1>COMMONS V5 공간 기본설계</h1><div>설계안 · 실제 런타임에 아직 반영하지 않았습니다.</div></header><main><section><button id="g">1층</button><button id="u">2층 / 확장 영역</button><button id="both">전체</button><button id="home">HOME 확대</button><button id="office">OFFICE 확대</button><button id="sports">SPORTS 확대</button><svg id="map" viewBox="-36 -48 117 110"></svg></section><aside><h2 id="name">방을 선택하세요</h2><div id="detail"></div><p class="note">빈 예약 영역과 실사용 방을 구분합니다. 이 도면은 법규 인증이나 완성 미술 검수 결과가 아닙니다.</p><h3>U 계단 단면 기준</h3><pre>3.60m ━━━━━ 2층 공용 복도\n         / 10단\n1.80m ━━━ 실제 계단참 1.5m\n      / 10단\n0.00m ━━━━━ 1층 홀\n20 × 0.18m / 디딤판 0.30m\n유효 폭 1.5m / 머리 여유 목표 2.2m\n상부 슬래브 개구부 + 난간 필수</pre><p>OFFICE · HOME · SPORTS는 재료, 동선, 음성 구역으로 분리합니다. 코트 관리자 검증과 문 잠금은 별개입니다.</p></aside></main><script>const P=__DATA__,svg=document.querySelector('#map'),ns='http://www.w3.org/2000/svg',colors={HOME:'#cfd9b7',OFFICE:'#bfdbdf',PUBLIC:'#dfd8bd',ADMIN:'#ecc8a7',PLAY:'#ccbce0',RESERVE:'#e1e4e4'};function node(t,a){let n=document.createElementNS(ns,t);for(let[k,v]of Object.entries(a))n.setAttribute(k,v);svg.append(n);return n}function draw(floor,wing=null){svg.replaceChildren();svg.setAttribute('viewBox',wing==='HOME'?'-30 -15 24 32':wing==='OFFICE'?'6 -42 36 60':wing==='ADMIN'?'-26 18 92 38':floor===0?'-30 -21 105 78':'-30 -42 67 60');for(let r of P.rooms){if(floor!==null&&r.y!==floor)continue;if(wing&&r.wing!==wing&&!(wing==='OFFICE'&&r.wing==='RESERVE'))continue;let[x,z,x2,z2]=r.rect,n=node('rect',{class:'room',x,y:z,width:x2-x,height:z2-z,fill:colors[r.wing],opacity:r.y&&floor===null?.55:1});n.onclick=()=>{document.querySelector('#name').textContent=r.name;document.querySelector('#detail').replaceChildren();for(let text of [`${x2-x} × ${z2-z}m · 바닥 Y ${r.y}m`,r.uses,`재료: ${r.finish||'해당 동의 공통 재료'}`,`문 중심: ${r.door?.join(', ')||'연속 공용 동선'}`,`창 계획: ${r.windows}`]){let p=document.createElement('p');p.textContent=text;document.querySelector('#detail').append(p)}};node('text',{x:x+.3,y:z+1.4}).textContent=r.name;if(r.door)node('circle',{cx:r.door[0],cy:r.door[1],r:.35,fill:'#fff',stroke:'#203934','stroke-width':.12})}node('text',{x:-34,y:-44}).textContent='북쪽 −Z / 단위 m';}document.querySelector('#g').onclick=()=>draw(0);document.querySelector('#u').onclick=()=>draw(3.6);document.querySelector('#both').onclick=()=>draw(null);document.querySelector('#home').onclick=()=>draw(0,'HOME');document.querySelector('#office').onclick=()=>draw(0,'OFFICE');document.querySelector('#sports').onclick=()=>draw(0,'ADMIN');draw(0);</script></html>'''
(out/'architecture-plan.html').write_text(html.replace('__DATA__',json.dumps(plan,ensure_ascii=False)),encoding='utf-8')
print('DESIGN_ONLY',len(rooms),'program/connection/reserved areas; runtime layout untouched')
