"""Draw the authored campus collision/room plan; never a substitute for runtime evidence."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'assets/v6/campus.json').read_text(encoding='utf-8'))
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>COMMONS · 층별 실행 도면</title><style>
body{margin:0;background:#f1e5d2;color:#344044;font:16px/1.7 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:32px}h1{font-size:34px;margin:0}p{max-width:900px}nav{display:flex;gap:7px;flex-wrap:wrap;margin:22px 0}button{font:inherit;padding:10px 18px;border:1px solid #819b7e;border-radius:8px;background:#fff8ec;cursor:pointer}button[aria-pressed=true]{background:#436d61;color:white}.layout{display:grid;grid-template-columns:2fr 1fr;gap:24px}svg{width:100%;background:#fffcf5;border-radius:16px}aside{padding:18px;background:#fff8ec;border-radius:16px}small{color:#5f6e65}.keys{display:flex;gap:15px;flex-wrap:wrap}i{display:inline-block;width:12px;height:12px;margin-right:5px}.note{font-size:13px}a{color:#436d61}@media(max-width:800px){.layout{grid-template-columns:1fr}}
</style><main><small>COMMONS / WARM CAMPUS · 실측 단위 m</small><h1>한 코어, 여덟 층</h1><p>같은 자리에 정렬된 두 계단·두 승강기·공용 화장실, 크기가 다른 회의실, 움직이지 않는 개인실 슬롯. 이 도면은 실제 <code>assets/v6/campus.json</code>의 좌표를 표시합니다. 보행·물리·화면 검수 결과는 별도 기록을 확인하세요.</p><nav id="floors"></nav><div class="layout"><svg id="plan" viewBox="0 0 720 700" role="img" aria-label="선택한 층의 실제 평면"></svg><aside><h2 id="title"></h2><p id="purpose"></p><div id="rooms"></div><hr><div class="keys"><span><i style="background:#819b7e"></i>승강기</span><span><i style="background:#c77c59"></i>계단</span><span><i style="background:#edbb58"></i>회의/개인실</span><span><i style="background:#b5bdb1"></i>실제 충돌체</span></div><p class="note">승강기는 실제 움직이는 바닥이며 층 선택 메뉴가 좌표를 순간이동하지 않습니다. 5층 홀은 공개, 운영실·방송실은 관리자 경계를 유지합니다. 옛 개인실 ID는 보존하고 배치가 겹치는 사물은 미배치 보관함에 남깁니다.</p><p class="note">가상 게임 설계이며 실제 건축·소방·접근성 인증을 뜻하지 않습니다.</p></aside></div><p><a href="design-decisions-ko.md">이미지 미술 분석</a> · <a href="verification-ko.md">V6 검수 기록</a></p></main><script>
const data=__DATA__;
const ns='http://www.w3.org/2000/svg',plan=document.querySelector('#plan');
function draw(type,attrs,text){const n=document.createElementNS(ns,type);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;plan.append(n);return n}
const x=v=>45+(v-8)*23,z=v=>35+(v+40)*23;
function rect(r,color,opacity=1){return draw('rect',{x:x(r[0]),y:z(r[1]),width:(r[2]-r[0])*23,height:(r[3]-r[1])*23,fill:color,'fill-opacity':opacity,stroke:color,'stroke-width':1})}
const purpose={'B1':'주차 구획과 수납, 유지보수 지원 공간. 현재 차량 운전이나 실제 서버 설비 조작 기능은 없습니다.','1F':'공개 도착 홀, 층 안내판, 카페 테이블과 대기석. HOME 동쪽 연결 통로에서 걸어서 접근합니다.','2F':'느티나무 10석, 이끼·흙빛 4석, 세미나 6석. 회의별 공동 문서·보드·원본 자료·발표를 분리합니다.','3F':'창가 팀 책상과 모니터, 프로젝트 자료 서가, 공용 협업 축.','4F':'8개의 고정 개인실 슬롯, 가운데 2.2m 갤러리, 동쪽 공용 접근로와 북쪽 자료·상담 공간.','5F':'운영실과 방송실의 검증된 관리자 출입, 별도의 공용 승강기 홀. 가상 CCTV는 공개 홀만 비춥니다.','6F':'식사 테이블, 기존 기능을 쓰는 실제 냉장고·조리·세척 설비, 셋백 테라스.','RF':'퍼골라·벤치·식재와 난간, 공용 화장실, 두 계단·두 승강기 출입 코어.'};
function show(id){plan.replaceChildren();const floor=data.floors.find(f=>f.id===id);document.querySelector('#title').textContent=id+' · '+floor.title;document.querySelector('#purpose').textContent=purpose[id];for(const b of document.querySelectorAll('nav button'))b.setAttribute('aria-pressed',String(b.dataset.id===id));rect([10,-38,36,-14],'#e9e2d4');
for(const c of data.collisions.filter(c=>c.floor===id&&c.size&&c.size[1]>.26)){const p=c.position,s=c.size;rect([p[0]-s[0]/2,p[2]-s[2]/2,p[0]+s[0]/2,p[2]+s[2]/2],'#a5afa0',.65)}
const rooms=id==='4F'?data.personalSlots:data.rooms.filter(r=>r.floor===id);const list=document.querySelector('#rooms');list.replaceChildren();for(const r of rooms){rect(r.rect,'#edbb58',.12);draw('text',{x:x((r.rect[0]+r.rect[2])/2),y:z((r.rect[1]+r.rect[3])/2),'text-anchor':'middle','font-size':13,fill:'#344044'},r.meetingId||r.id);const p=document.createElement('p');p.textContent=r.meetingId||r.id;list.append(p)}
for(const h of data.stairHoles)rect(h,'#c77c59',.6);for(const l of data.lifts){rect([l.x-l.width/2,-36.3,l.x+l.width/2,-33.3],'#819b7e');draw('text',{x:x(l.x),y:z(-34.7),'text-anchor':'middle','font-size':12,fill:'white'},l.id==='service'?'운반':'승객')}
for(const f of data.furniture.filter(f=>f.floor===id))draw('circle',{cx:x(f.p[0]),cy:z(f.p[2]),r:5,fill:'#436d61'});
draw('text',{x:45,y:22,'font-size':13},'북 ↑');draw('text',{x:x(23),y:z(-12.8),'text-anchor':'middle','font-size':13},'남 / HOME 공용 보행로');draw('line',{x1:x(10),x2:x(15),y1:665,y2:665,stroke:'#344044','stroke-width':3});draw('text',{x:x(12.5),y:687,'text-anchor':'middle','font-size':12},'5m');}
for(const f of data.floors){const b=document.createElement('button');b.dataset.id=f.id;b.textContent=f.id;b.onclick=()=>show(f.id);document.querySelector('#floors').append(b)}show('2F');
</script></html>'''
(root/'docs/v6/campus-plan.html').write_text(page.replace('__DATA__',json.dumps(data,ensure_ascii=False)),encoding='utf-8')
print('Wrote authored campus plan')
